# Generated by Django 5.2.10 on 2026-02-02 09:16

import apps.core.models
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAssessmentResponse',
            fields=[
                ('id', models.CharField(db_index=True, default=apps.core.models.cuid_generator, editable=False, max_length=30)),
                ('response', models.CharField(choices=[('yes', 'Yes, I have done this'), ('partially', 'Partially / Sometimes'), ('no', 'No, never')], max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('candidate', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='candidates.candidateprofile')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='content.occupationtask')),
            ],
            options={
                'verbose_name': 'historical Assessment Response',
                'verbose_name_plural': 'historical Assessment Responses',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='AssessmentResponse',
            fields=[
                ('id', models.CharField(default=apps.core.models.cuid_generator, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('response', models.CharField(choices=[('yes', 'Yes, I have done this'), ('partially', 'Partially / Sometimes'), ('no', 'No, never')], max_length=20)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_responses', to='candidates.candidateprofile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_responses', to='content.occupationtask')),
            ],
            options={
                'verbose_name': 'Assessment Response',
                'verbose_name_plural': 'Assessment Responses',
                'unique_together': {('candidate', 'task')},
            },
        ),
    ]
