# Generated by Django 5.2.10 on 2026-02-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_historicalassessmentresponse_assessmentresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='assessment_progress',
            field=models.JSONField(blank=True, default=dict, help_text='Progress stats per occupation'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='highest_nqf_level',
            field=models.CharField(blank=True, help_text='Cached highest NQF level', max_length=50),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='occupation_matches_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of occupation matches found'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='recommended_occupations',
            field=models.JSONField(blank=True, default=list, help_text='List of recommended occupation IDs or details'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='stats_last_computed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='stats_update_needed',
            field=models.BooleanField(default=True, help_text='Flag to trigger stats re-computation'),
        ),
        migrations.AddField(
            model_name='historicalcandidateprofile',
            name='assessment_progress',
            field=models.JSONField(blank=True, default=dict, help_text='Progress stats per occupation'),
        ),
        migrations.AddField(
            model_name='historicalcandidateprofile',
            name='highest_nqf_level',
            field=models.CharField(blank=True, help_text='Cached highest NQF level', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalcandidateprofile',
            name='occupation_matches_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of occupation matches found'),
        ),
        migrations.AddField(
            model_name='historicalcandidateprofile',
            name='recommended_occupations',
            field=models.JSONField(blank=True, default=list, help_text='List of recommended occupation IDs or details'),
        ),
        migrations.AddField(
            model_name='historicalcandidateprofile',
            name='stats_last_computed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcandidateprofile',
            name='stats_update_needed',
            field=models.BooleanField(default=True, help_text='Flag to trigger stats re-computation'),
        ),
    ]
