# Generated by Django 5.2.10 on 2026-02-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_candidateprofile_assessment_progress_and_more'),
        ('storage', '0002_historicalfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='files',
            field=models.ManyToManyField(blank=True, help_text='Optional files attached to this candidate profile', related_name='candidate_profiles', to='storage.file'),
        ),
    ]
