# Generated by Django 5.2.10 on 2026-02-02 07:13

import apps.core.models
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.CharField(default=apps.core.models.cuid_generator, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('ofo_code', models.CharField(max_length=20, unique=True)),
                ('ofo_title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('years_of_experience', models.PositiveIntegerField(default=0, help_text='Typical years of experience required')),
            ],
            options={
                'verbose_name': 'Occupation',
                'verbose_name_plural': 'Occupations',
                'ordering': ['ofo_code'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.CharField(default=apps.core.models.cuid_generator, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalOccupation',
            fields=[
                ('id', models.CharField(db_index=True, default=apps.core.models.cuid_generator, editable=False, max_length=30)),
                ('ofo_code', models.CharField(db_index=True, max_length=20)),
                ('ofo_title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('years_of_experience', models.PositiveIntegerField(default=0, help_text='Typical years of experience required')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Occupation',
                'verbose_name_plural': 'historical Occupations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSkill',
            fields=[
                ('id', models.CharField(db_index=True, default=apps.core.models.cuid_generator, editable=False, max_length=30)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Skill',
                'verbose_name_plural': 'historical Skills',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalOccupationTask',
            fields=[
                ('id', models.CharField(db_index=True, default=apps.core.models.cuid_generator, editable=False, max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('occupation', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='content.occupation')),
            ],
            options={
                'verbose_name': 'historical Occupation Task',
                'verbose_name_plural': 'historical Occupation Tasks',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='OccupationTask',
            fields=[
                ('id', models.CharField(default=apps.core.models.cuid_generator, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='content.occupation')),
                ('skills', models.ManyToManyField(blank=True, related_name='tasks', to='content.skill')),
            ],
            options={
                'verbose_name': 'Occupation Task',
                'verbose_name_plural': 'Occupation Tasks',
                'ordering': ['occupation', 'title'],
            },
        ),
    ]
