# Generated by Django 5.2.10 on 2026-02-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_industry_historicalindustry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloccupation',
            name='preferred_nqf_level',
            field=models.PositiveIntegerField(default=0, help_text='Preferred NQF level (0=Any, 4=Matric, 5=Certificate, 6=Diploma, 7=Degree, 8=Honours, 9=Masters, 10=Doctorate)'),
        ),
        migrations.AddField(
            model_name='occupation',
            name='preferred_nqf_level',
            field=models.PositiveIntegerField(default=0, help_text='Preferred NQF level (0=Any, 4=Matric, 5=Certificate, 6=Diploma, 7=Degree, 8=Honours, 9=Masters, 10=Doctorate)'),
        ),
    ]
