# Generated by Django 5.2.10 on 2026-02-10 06:42

import apps.core.models
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0003_add_preferred_nqf_level"),
        ("storage", "0002_historicalfile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="occupation",
            name="files",
            field=models.ManyToManyField(
                blank=True,
                help_text="Optional files attached to this occupation",
                related_name="occupations",
                to="storage.file",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalOccupationMedia",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_index=True,
                        default=apps.core.models.cuid_generator,
                        editable=False,
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("pdf", "PDF Document"),
                            ("image", "Image"),
                            ("audio", "Audio"),
                            ("link", "External Link"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("remote", "Remote URL (YouTube, Vimeo, etc.)"),
                            ("local", "Local File Storage"),
                        ],
                        default="remote",
                        max_length=20,
                    ),
                ),
                (
                    "remote_url",
                    models.URLField(
                        blank=True,
                        help_text="URL for remote media (YouTube, Vimeo, etc.)",
                    ),
                ),
                (
                    "embed_code",
                    models.TextField(
                        blank=True,
                        help_text="Optional embed HTML code for remote media",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Show as featured media"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Media is visible to candidates"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "local_file",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Local file from storage",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="storage.file",
                    ),
                ),
                (
                    "occupation",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="content.occupation",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Occupation Media",
                "verbose_name_plural": "historical Occupation Media",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="OccupationMedia",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.core.models.cuid_generator,
                        editable=False,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("pdf", "PDF Document"),
                            ("image", "Image"),
                            ("audio", "Audio"),
                            ("link", "External Link"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("remote", "Remote URL (YouTube, Vimeo, etc.)"),
                            ("local", "Local File Storage"),
                        ],
                        default="remote",
                        max_length=20,
                    ),
                ),
                (
                    "remote_url",
                    models.URLField(
                        blank=True,
                        help_text="URL for remote media (YouTube, Vimeo, etc.)",
                    ),
                ),
                (
                    "embed_code",
                    models.TextField(
                        blank=True,
                        help_text="Optional embed HTML code for remote media",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Show as featured media"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Media is visible to candidates"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "local_file",
                    models.ForeignKey(
                        blank=True,
                        help_text="Local file from storage",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="occupation_media",
                        to="storage.file",
                    ),
                ),
                (
                    "occupation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_items",
                        to="content.occupation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Occupation Media",
                "verbose_name_plural": "Occupation Media",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
