# Generated by Django 5.2.10 on 2026-02-10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0004_occupation_files_historicaloccupationmedia_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="occupationmedia",
            name="is_global",
            field=models.BooleanField(
                default=False,
                help_text="Visible to all candidates in the content feed",
            ),
        ),
    ]
