# Generated by Django 5.2.10 on 2026-02-10 06:55

from django.db import migrations


def seed_feature_flags(apps, schema_editor):
    FeatureFlag = apps.get_model("core", "FeatureFlag")
    FeatureFlag.objects.get_or_create(
        key="content_feed",
        defaults={
            "name": "Content Feed",
            "description": "Enable the candidate content feed experience.",
            "is_enabled": True,
        },
    )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_historicalfeatureflag"),
    ]

    operations = [
        migrations.RunPython(seed_feature_flags, migrations.RunPython.noop),
    ]
