# Generated by Django 5.2.10 on 2026-02-01 11:02

import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.core.models.cuid_generator,
                        editable=False,
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/%Y/%m/%d/")),
                (
                    "display_name",
                    models.CharField(help_text="Human readable name", max_length=255),
                ),
                (
                    "original_name",
                    models.CharField(
                        blank=True,
                        help_text="Original filename on upload",
                        max_length=255,
                    ),
                ),
                ("extension", models.CharField(blank=True, max_length=50)),
                ("mimetype", models.CharField(blank=True, max_length=100)),
                (
                    "size",
                    models.PositiveBigIntegerField(
                        default=0, help_text="Size in bytes"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "File",
                "verbose_name_plural": "Files",
                "ordering": ["-created_at"],
            },
        ),
    ]
