# Generated by Django 5.2.10 on 2026-02-01 11:45

import apps.core.models
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalFile',
            fields=[
                ('id', models.CharField(db_index=True, default=apps.core.models.cuid_generator, editable=False, max_length=30)),
                ('file', models.TextField(max_length=100)),
                ('display_name', models.CharField(help_text='Human readable name', max_length=255)),
                ('original_name', models.CharField(blank=True, help_text='Original filename on upload', max_length=255)),
                ('extension', models.CharField(blank=True, max_length=50)),
                ('mimetype', models.CharField(blank=True, max_length=100)),
                ('size', models.PositiveBigIntegerField(default=0, help_text='Size in bytes')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical File',
                'verbose_name_plural': 'historical Files',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
